[package]
name = "flux-server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
description = "Server implementation for Flux real-time communication"

[dependencies]
# Internal dependencies

# External dependencies
redis = { workspace = true}
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.15"
futures = "0.3"
log = "0.4"
env_logger = "0.9"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
sha1 = "0.10"
base64 = "0.21"
uuid.workspace = true

[dev-dependencies]
tokio-test = { workspace = true }
