[package]
name = "flux-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tungstenite = "0.15"
redis = "0.23"
mysql_async = "0.32"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
async-trait = "0.1.88"
argon2 = "0.5"
rand_core = "0.6"
password-hash = "0.5"
axum = { version = "0.7", features = ["ws", "tokio"] }
tower-sessions = { version = "0.12", features = ["memory-store"] }
